from django.urls import path, register_converter
from . import views, converters

register_converter(converters.FloatUrlParameterConverter, "float")

urlpatterns = [
    path(
        "add-two-numbers/<int:first_number>/<int:second_number>/",
        views.AddTwoNumbersView.as_view(),
        name="AddTwoNumbersView",
    ),
    path(
        "convert-binary-to-decimal/<str:binary_number>/",
        views.ConvertBinaryToDecimalView.as_view(),
        name="ConvertBinaryToDecimalView",
    ),
    path(
        "convert-binary-to-hexadecimal/<str:binary_number>/",
        views.ConvertBinaryToHexadecimalView.as_view(),
        name="ConvertBinaryToHexadecimalView",
    ),
    path(
        "convert-binary-to-octal/<str:binary_number>/",
        views.ConvertBinaryToOctalView.as_view(),
        name="ConvertBinaryToOctalView",
    ),
    path(
        "convert-celsius-to-fahrenheit/<float:celsius>/",
        views.ConvertCelsiusToFahrenheitView.as_view(),
        name="ConvertCelsiusToFahrenheitView",
    ),
    path(
        "convert-centimeters-to-feet/<float:centimeters>/",
        views.ConvertCentimetersToFeetView.as_view(),
        name="ConvertCentimetersToFeetView",
    ),
    path(
        "convert-centimeters-to-inches/<float:centimeters>/",
        views.ConvertCentimetersToInchesView.as_view(),
        name="ConvertCentimetersToInchesView",
    ),
    path(
        "convert-days-to-hours/<int:days>/",
        views.ConvertDaysToHoursView.as_view(),
        name="ConvertDaysToHoursView",
    ),
    path(
        "convert-days-to-minutes/<int:days>/",
        views.ConvertDaysToMinutesView.as_view(),
        name="ConvertDaysToMinutesView",
    ),
    path(
        "convert-days-to-seconds/<int:days>/",
        views.ConvertDaysToSecondsView.as_view(),
        name="ConvertDaysToSecondsView",
    ),
    path(
        "convert-decimal-to-binary/<int:decimal_number>/",
        views.ConvertDecimalToBinaryView.as_view(),
        name="ConvertDecimalToBinaryView",
    ),
    path(
        "convert-decimal-to-hexadecimal/<int:decimal_number>/",
        views.ConvertDecimalToHexadecimalView.as_view(),
        name="ConvertDecimalToHexadecimalView",
    ),
    path(
        "convert-decimal-to-octal/<int:decimal_number>/",
        views.ConvertDecimalToOctalView.as_view(),
        name="ConvertDecimalToOctalView",
    ),
    path(
        "convert-hexadecimal-to-binary/<str:hexadecimal_number>/",
        views.ConvertHexadecimalToBinaryView.as_view(),
        name="ConvertHexadecimalToBinaryView",
    ),
    path(
        "convert-hexadecimal-to-decimal/<str:hexadecimal_number>/",
        views.ConvertHexadecimalToDecimalView.as_view(),
        name="ConvertHexadecimalToDecimalView",
    ),
    path(
        "convert-hexadecimal-to-octal/<str:hexadecimal_number>/",
        views.ConvertHexadecimalToOctalView.as_view(),
        name="ConvertHexadecimalToOctalView",
    ),
    path(
        "convert-octal-to-binary/<int:octal_number>/",
        views.ConvertOctalToBinaryView.as_view(),
        name="ConvertOctalToBinaryView",
    ),
    path(
        "convert-octal-to-decimal/<int:octal_number>/",
        views.ConvertOctalToDecimalView.as_view(),
        name="ConvertOctalToDecimalView",
    ),
    path(
        "convert-octal-to-hexadecimal/<int:octal_number>/",
        views.ConvertOctalToHexadecimalView.as_view(),
        name="ConvertOctalToHexadecimalView",
    ),
    path(
        "format-to-camelcase/<str:input_string>/",
        views.FormatToCamelCaseView.as_view(),
        name="FormatToCamelCaseView",
    ),
    path(
        "format-to-constantcase/<str:input_string>/",
        views.FormatToConstantCaseView.as_view(),
        name="FormatToConstantCaseView",
    ),
    path(
        "format-to-dotcase/<str:input_string>/",
        views.FormatToDotCaseView.as_view(),
        name="FormatToDotCaseView",
    ),
    path(
        "format-to-kebabcase/<str:input_string>/",
        views.FormatToKebabCaseView.as_view(),
        name="FormatToKebabCaseView",
    ),
    path(
        "format-to-pascalcase/<str:input_string>/",
        views.FormatToPascalCaseView.as_view(),
        name="FormatToPascalCaseView",
    ),
    path(
        "format-to-pathcase/<str:input_string>/",
        views.FormatToPathCaseView.as_view(),
        name="FormatToPathCaseView",
    ),
    path(
        "format-to-snakecase/<str:input_string>/",
        views.FormatToSnakeCaseView.as_view(),
        name="FormatToSnakeCaseView",
    ),
    path(
        "format-to-titlecase/<str:input_string>/",
        views.FormatToTitleCaseView.as_view(),
        name="FormatToTitleCaseView",
    ),
    path(
        "substract-two-numbers/<int:first_number>/<int:second_number>/",
        views.SubstractTwoNumbersView.as_view(),
        name="SubstractTwoNumbersView",
    ),
]
