# Generated by Django 4.1.3 on 2022-12-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GithubUserModel",
            fields=[
                (
                    "username",
                    models.CharField(
                        default="",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Github User",
                "verbose_name_plural": "Github Users",
            },
        ),
        migrations.CreateModel(
            name="ToolCategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=255)),
            ],
            options={
                "verbose_name": "Tool Category",
                "verbose_name_plural": "Tool Categories",
            },
        ),
        migrations.CreateModel(
            name="ToolPackageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=255)),
            ],
            options={
                "verbose_name": "Tool Package",
                "verbose_name_plural": "Tool Packages",
            },
        ),
        migrations.CreateModel(
            name="ToolModel",
            fields=[
                (
                    "slug",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("title", models.CharField(default="", max_length=255)),
                ("description", models.TextField(default="")),
                ("markdown", models.TextField(default="")),
                ("last_updated", models.DateTimeField(default=None, null=True)),
                ("rating", models.FloatField(default=0)),
                ("rating_count", models.IntegerField(default=0)),
                ("views", models.IntegerField(default=0)),
                ("used", models.IntegerField(default=0)),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="tools", to="tools_data.toolcategorymodel"
                    ),
                ),
                (
                    "contributors",
                    models.ManyToManyField(
                        related_name="tools", to="tools_data.githubusermodel"
                    ),
                ),
                (
                    "package",
                    models.ManyToManyField(
                        related_name="tools", to="tools_data.toolpackagemodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tool",
                "verbose_name_plural": "Tools",
            },
        ),
    ]
