# Generated by Django 4.1.3 on 2023-01-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools_data", "0002_testimonialmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolmodel",
            name="js",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="toolmodel",
            name="py",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="toolmodel",
            name="sh",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="toolmodel",
            name="ts",
            field=models.TextField(default=""),
        ),
    ]
